#!/usr/bin/env bash
#This script displays numbers from 1-100 and filters multiples of 3 & 5

number=1

while [ "$number" -le 100 ];do
	if [ $(( number % 15 )) -eq 0 ];then	
		echo "FizzBuzz"
	elif [ $(( number % 3)) -eq 0 ];then
		echo "Fizz"
	elif [ $(( number % 5)) -eq 0 ];then
		echo "Buzz"
	else
		echo "$number"
	fi
	number=$(( number + 1 ))

done
