#!/usr/bin/env bash

#Script to display time for 12 hours and 59 minutes

minutes=0

while [ $minutes -le 779 ]
do

	case $minutes in
	0) echo "Hour: 0";;
	60) echo "Hour: 1";;
	120) echo "Hour: 2";;
	180) echo "Hour: 3";;
	240) echo "Hour: 4";;
	300) echo "Hour: 5";;
	360) echo "Hour: 6";;
	420) echo "Hour: 7";;
	480) echo "Hour: 8";;
	540) echo "Hour: 9";;
	600) echo "Hour: 10";;
	660) echo "Hour: 11";;
	720) echo "Hour: 12";;
	*) echo "$minutes";; 
	esac

	minutes=$(( minutes + 1 ))
	sleep 0
done
