#!/usr/bin/env bash
#This script lists all files that are not hidden and removes number from filename
for file in *; do
    if [[ "$file" == .* ]]; then
        continue
    fi
    if [[ "$file" == *-* ]]; then
        echo "${file#*-}"
    else
        echo "$file"
    fi
done
