#!/usr/bin/env bash
# Script: 7-highlander

# Trap SIGTERM and print "I am invincible!!!" instead of terminating
trap 'echo "I am invincible!!!"' SIGTERM

# Infinite loop with "To infinity and beyond" and sleep
while true; do
    echo "To infinity and beyond"
    sleep 2
done
